---
title: "Grinding Robot Performance (hr)"
author: "Natnalin Kerdkaew"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
```

### **Assume the Data**
```{r}
# Create List
time_before <- c(1:8)
work_before <- c(10, 12, 13, 12, 14, 15, 11, 13)
time_after <- c(1:8)
work_after <- c(12, 13, 15, 12, 15, 16, 12, 15)

# Create Data Frame
work_data <- data.frame(
  time_before = time_before,
  work_before = work_before,
  time_after = time_after,
  work_after = work_after
)
```

### **Create Graph**

```{r}
# Create Graph
work_data_graph1 <- ggplot(work_data) +
  geom_line(aes(x = time_before, y = work_before, color = "Before")) +
  geom_line(aes(x = time_after, y = work_after, color = "After")) +
  labs(x = "Time (hr)", y = "Works (%)", title = "Work Before and After Install Grinding Robot") +
  scale_color_manual(name = "Legend", values = c("Before" = "gold", "After" = "purple")) +
  theme_minimal()
print(work_data_graph1)

```

### **Percent of Change per Hour**

```{r}
# Calculate percent of change
work_data$percent_change <- ((work_data$work_after - work_data$work_before) / work_data$work_before) * 100
work_data

```

### **Total Percent of Change**

```{r}
# Calculate the sum of work_before and work_after
total_work_before <- sum(work_data$work_before)
total_work_after <- sum(work_data$work_after)

# Calculate the total percent change
total_percent_change <- ((total_work_after - total_work_before) / total_work_before) * 100
total_percent_change

```

